steps:
- name: 'gcr.io/cloud-builders/gsutil'
script: |
#!/bin/bash
while read PYTHON
do
echo $PYTHON
gsutil cp *.py gs://us-east4-comp-eus4-edw-dev--4cf5d816-bucket/dags/composer_test
done < release.txt
options:
logging: CLOUD_LOGGING_ONLY
dynamic_substitutions: true
