steps: 
  - name: 'gcr.io/cloud-builders/gsutil'
    script: |
     #!/bin/bash
     while read PYTHON
     do
      echo $PYTHON
      cat release.txt | gsutil -m cp -I gs://composer_dev
     done < release.txt
options:
      logging: CLOUD_LOGGING_ONLY
      dynamic_substitutions: true
